# Generated by Django 5.2.4 on 2025-08-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre_edificio', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('cantidad_pisos', models.PositiveIntegerField()),
                ('cantidad_departamentos', models.PositiveIntegerField()),
            ],
        ),
    ]
