# Generated by Django 5.2.5 on 2025-08-15 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre_edificio', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('cantidad_pisos', models.PositiveIntegerField()),
                ('cantidad_departamentos', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('planificacion', '📋 Planificación'), ('aprobado', '✅ Aprobado'), ('en_construccion', '🏗️ En Construcción'), ('paralizado', '⚠️ Paralizado'), ('completado', '🎉 Completado'), ('cancelado', '❌ Cancelado')], default='planificacion', max_length=20, verbose_name='Estado del Proyecto')),
                ('prioridad', models.CharField(choices=[('alta', '🔴 Alta'), ('media', '🟡 Media'), ('baja', '🟢 Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Finalización')),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto Estimado (S/)')),
                ('presupuesto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto Gastado (S/)')),
                ('progreso_porcentaje', models.PositiveIntegerField(default=0, help_text='Porcentaje de avance del proyecto (0-100)', verbose_name='Progreso (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('estado_anterior', models.CharField(blank=True, choices=[('planificacion', '📋 Planificación'), ('aprobado', '✅ Aprobado'), ('en_construccion', '🏗️ En Construcción'), ('paralizado', '⚠️ Paralizado'), ('completado', '🎉 Completado'), ('cancelado', '❌ Cancelado')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('planificacion', '📋 Planificación'), ('aprobado', '✅ Aprobado'), ('en_construccion', '🏗️ En Construcción'), ('paralizado', '⚠️ Paralizado'), ('completado', '🎉 Completado'), ('cancelado', '❌ Cancelado')], max_length=20, verbose_name='Estado Nuevo')),
                ('progreso_anterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='Progreso Anterior (%)')),
                ('progreso_nuevo', models.PositiveIntegerField(verbose_name='Progreso Nuevo (%)')),
                ('comentario', models.TextField(verbose_name='Comentarios del Cambio')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registra')),
            ],
            options={
                'verbose_name': 'Seguimiento de Proyecto',
                'verbose_name_plural': 'Seguimientos de Proyectos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='TareaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('en_progreso', '🔄 En Progreso'), ('completada', '✅ Completada'), ('bloqueada', '🚫 Bloqueada')], default='pendiente', max_length=15, verbose_name='Estado de la Tarea')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de Ejecución')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Tarea de Proyecto',
                'verbose_name_plural': 'Tareas de Proyectos',
                'ordering': ['proyecto', 'orden'],
            },
        ),
    ]
