# Generated by Django 5.2.5 on 2025-08-06 14:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('planificacion', '📋 Planificación'), ('aprobado', '✅ Aprobado'), ('en_construccion', '🏗️ En Construcción'), ('paralizado', '⚠️ Paralizado'), ('completado', '🎉 Completado'), ('cancelado', '❌ Cancelado')], default='planificacion', max_length=20, verbose_name='Estado del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 6, 14, 28, 4, 849866, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Real de Finalización'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones Generales'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto Estimado (S/)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto_gastado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto Gastado (S/)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.CharField(choices=[('alta', '🔴 Alta'), ('media', '🟡 Media'), ('baja', '🟢 Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='progreso_porcentaje',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de avance del proyecto (0-100)', verbose_name='Progreso (%)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Proyecto'),
        ),
        migrations.CreateModel(
            name='SeguimientoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('estado_anterior', models.CharField(blank=True, choices=[('planificacion', '📋 Planificación'), ('aprobado', '✅ Aprobado'), ('en_construccion', '🏗️ En Construcción'), ('paralizado', '⚠️ Paralizado'), ('completado', '🎉 Completado'), ('cancelado', '❌ Cancelado')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('planificacion', '📋 Planificación'), ('aprobado', '✅ Aprobado'), ('en_construccion', '🏗️ En Construcción'), ('paralizado', '⚠️ Paralizado'), ('completado', '🎉 Completado'), ('cancelado', '❌ Cancelado')], max_length=20, verbose_name='Estado Nuevo')),
                ('progreso_anterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='Progreso Anterior (%)')),
                ('progreso_nuevo', models.PositiveIntegerField(verbose_name='Progreso Nuevo (%)')),
                ('comentario', models.TextField(verbose_name='Comentarios del Cambio')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registra')),
            ],
            options={
                'verbose_name': 'Seguimiento de Proyecto',
                'verbose_name_plural': 'Seguimientos de Proyectos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='TareaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('en_progreso', '🔄 En Progreso'), ('completada', '✅ Completada'), ('bloqueada', '🚫 Bloqueada')], default='pendiente', max_length=15, verbose_name='Estado de la Tarea')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de Ejecución')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Tarea de Proyecto',
                'verbose_name_plural': 'Tareas de Proyectos',
                'ordering': ['proyecto', 'orden'],
            },
        ),
    ]
