# Generated by Django 5.2.4 on 2025-08-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Esta migración está vacía porque roles no tiene modelos propios
        # Solo maneja Groups y Permissions de Django
    ]
