# Generated by Django 5.2.4 on 2025-08-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableTroncal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('capacidad', models.IntegerField(choices=[(12, '12 hilos'), (24, '24 hilos'), (48, '48 hilos'), (64, '64 hilos'), (96, '96 hilos'), (128, '128 hilos')], verbose_name='Capacidad (hilos)')),
            ],
            options={
                'verbose_name': 'Cable Troncal',
                'verbose_name_plural': 'Cables Troncales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Mufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('troncal', 'Mufa Troncal'), ('derivacion', 'Mufa de Derivación'), ('final', 'Mufa Final User')], default='troncal', max_length=20, verbose_name='Tipo de Mufa')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('capacidad_hilos', models.IntegerField(choices=[(12, '12 hilos'), (24, '24 hilos'), (48, '48 hilos'), (64, '64 hilos'), (96, '96 hilos'), (128, '128 hilos')], default=12, verbose_name='Capacidad de hilos')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('cable_troncal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mufas', to='mufas.cabletroncal', verbose_name='Cable Troncal')),
            ],
            options={
                'verbose_name': 'Mufa',
                'verbose_name_plural': 'Mufas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Nº de hilo')),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado')], default='libre', max_length=50, verbose_name='Estado')),
                ('uso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uso/Proyecto')),
                ('splitter', models.CharField(choices=[('1:1', '1:1'), ('1:4', '1:4'), ('1:8', '1:8'), ('-', 'Sin splitter')], default='-', max_length=10, verbose_name='Splitter')),
                ('destino', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destino')),
                ('mufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hilos', to='mufas.mufa', verbose_name='Mufa')),
            ],
            options={
                'verbose_name': 'Hilo',
                'verbose_name_plural': 'Hilos',
                'ordering': ['mufa', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_origen', to='mufas.hilo', verbose_name='Hilo Origen')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_destino', to='mufas.hilo', verbose_name='Hilo Destino')),
            ],
            options={
                'verbose_name': 'Conexión',
                'verbose_name_plural': 'Conexiones',
                'ordering': ['origen__mufa__codigo', 'origen__numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='hilo',
            constraint=models.UniqueConstraint(fields=('mufa', 'numero'), name='unique_mufa_numero'),
        ),
        migrations.AddConstraint(
            model_name='conexion',
            constraint=models.UniqueConstraint(fields=('origen', 'destino'), name='unique_conexion'),
        ),
    ]