# Generated by Django 5.2.5 on 2025-08-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mufas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conexion',
            name='unique_conexion',
        ),
        migrations.RemoveConstraint(
            model_name='hilo',
            name='unique_mufa_numero',
        ),
        migrations.AlterUniqueTogether(
            name='conexion',
            unique_together={('origen', 'destino')},
        ),
        migrations.AlterUniqueTogether(
            name='hilo',
            unique_together={('mufa', 'numero')},
        ),
    ]
