# Generated by Django 5.2.5 on 2025-08-15 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('comercial', 'Área Comercial'), ('planificacion', 'Área de Planificación'), ('construccion', 'Área de Construcción'), ('administracion', 'Administración')], max_length=20, unique=True, verbose_name='Código del Área')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Área Activa')),
            ],
            options={
                'verbose_name': 'Área de Trabajo',
                'verbose_name_plural': 'Áreas de Trabajo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción Realizada')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('detalles', models.TextField(blank=True, verbose_name='Detalles de la Acción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('comercial', 'Comercial'), ('supervisor_comercial', 'Supervisor Comercial'), ('planificador', 'Planificador'), ('supervisor_planificacion', 'Supervisor de Planificación'), ('constructor', 'Constructor'), ('supervisor_construccion', 'Supervisor de Construcción'), ('admin_sistema', 'Administrador del Sistema')], max_length=30, unique=True, verbose_name='Código del Rol')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Rol')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='roles.areatrabajo', verbose_name='Área de Trabajo')),
                ('permisos_especiales', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permisos Especiales')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'ordering': ['area', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('dni', models.CharField(blank=True, max_length=8, verbose_name='DNI')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('puede_ver_dashboard', models.BooleanField(default=True)),
                ('puede_crear_proyectos', models.BooleanField(default=False)),
                ('puede_editar_proyectos', models.BooleanField(default=False)),
                ('puede_asignar_hilos', models.BooleanField(default=False)),
                ('puede_ver_mapa_mufas', models.BooleanField(default=True)),
                ('puede_ver_analytics', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='roles.rolusuario', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['rol__area', 'usuario__username'],
            },
        ),
    ]
